### ISSUE TITLE
Package 'cl' is deprecated in Emacs 27

### ISSUE THREAD

**Issue by robertgrabowski** [acrolinx/acrolinx-mode.el#4]
When loading `acrolinx.el` in Emacs 27, a warning appears: `Package cl is deprecated`.

The reason is that `acrolinx.el` depends on the package `cl`, which is officially deprecated as of Emacs 27.1 in favour of `cl-lib`. [1]

Can acrolinx.el be updated to use `cl-lib` instead of `cl`?

[1] https://www.gnu.org/software/emacs/news/NEWS.27.1

**Comment by ska2342** [comment]
Done as part of PR #5
